name: vibration
description: A plugin for handling Vibration API on iOS, Android, and web.
version: 2.0.0
homepage: https://github.com/benjamindean/flutter_vibration

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.benjaminabel.vibration
        pluginClass: VibrationPlugin
      ios:
        pluginClass: VibrationPlugin
